CitizenApp/urls.py
from django.urls import path, include
from . import views as citizen_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'CitizenApp'
urlpatterns = [
    path('profile/', citizen_views.CitizenProfile, name='CitizenProfile'),
    path('login/', citizen_views.CitizenLogin, name='CitizenLogin'),
    path('logout/', citizen_views.CitizenLogout, name='CitizenLogout'),
    path('EditCitizen/<int:id>', citizen_views.CitizenEdit, name='CitizenEdit'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, name='uploads')

PoliceOfficerApp/urls.py
from django.urls import path, include
from . import views as officer_views
from django.conf import settings
from django.conf.urls.static import static

app_name = "PoliceOfficerApp"
urlpatterns = [
    path('', officer_views.index, name='OfficerDashboard'),
    path('OfficersDisplay/', officer_views.OfficersDisplay, name='OfficersDisplay'),
    path('OfficerProfile/', officer_views.OfficerProfile, name='OfficerProfile'),
    path('CitizensDisplay/', officer_views.CitizensDisplay, name='CitizensDisplay'),
    path('CrimesDisplay/', officer_views.CrimesDisplay, name='CrimesDisplay'),
    path('criminalbooking/', officer_views.criminalbooking, name='criminalbooking'),
    path('CriminalsDisplay/', officer_views.CriminalsDisplay, name='CriminalsDisplay'),
    path('CrimeListDisplay/', officer_views.CrimeListDisplay, name='CrimeListDisplay'),
    path('PoliceStation/', officer_views.PoliceStation, name='PoliceStation'),
    path('ViewStations/', officer_views.ViewStations, name='ViewStations'),
    path('login/', officer_views.login, name='OfficerLogin'),
    path('addCrimes/', officer_views.addCrimes, name='addCrimes'),

    path('case/', officer_views.CaseIndex, name='CaseIndex'),

    path('casetransfer/<int:id>', officer_views.CaseTransfer, name='CaseTransfer'),
    path('ob/<int:id>', officer_views.obDisplay, name='ob'),
    path('viewCase/<int:id>', officer_views.ViewCase, name='ViewCase'),
    path('approveCase/<int:id>', officer_views.ApproveCase, name='ApproveCase'),
    path('viewOB/<int:id>', officer_views.ViewOB, name='ViewOB'),
    path('showStation/<int:id>', officer_views.ShowStation, name='ShowStation'),
    path('generateCase/<int:id>', officer_views.GenerateCase, name='GenerateCase'),
    # CriminalEdit and update paths
    path('EditCriminal/<int:id>', officer_views.CriminalEdit, name='CriminalEdit'),
    path('EditOfficer/<int:id>', officer_views.OfficerEdit, name='OfficerEdit'),

    path('OfficerRegister/', officer_views.OfficerRegister, name='OfficerRegister'),
    path('logout/', officer_views.OfficerLogout, name='OfficerLogout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

police_system/urls.py
from django.contrib import admin
from django.urls import path, include
from records import views as record_views
from django.conf import settings
from django.conf.urls.static import static

app_name='PoliceSystem'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('evidence/',record_views.evidence, name='evidence'),
    path('crimereport/', record_views.CrimeListDisplay, name='crimereport'),
    path('issueforms/', record_views.issueforms, name='issueforms'),
    path('signup/',record_views.signup, name='userSignUp'),
    path('',record_views.landingpage, name='index'),
    path('citizen/', include('CitizenApp.urls'), name='citizen'),
    path('policeofficer/', include('PoliceOfficerApp.urls'), name='policeofficer')
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

PoliceOfficerApp/models.py
from django.db import models

# Create your models here.

PoliceOfficerApp/forms.py
from django import forms
from records.models import Criminal as CriminalModel

# created a new form for all the fields in the Criminal Model
class EditForm(forms.ModelForm):

    class Meta:
        model = CriminalModel
        fields= "__all__"

PoliceOfficerApp/views.py
import json
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.hashers import check_password, make_password
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.utils.datastructures import MultiValueDictKeyError
from records.models import Officer as OfficerModel, Case as CaseModel, PoliceStation as PoliceStationModel, CrimeAnonymous as CrimeAnonymousModel, Crime as CrimeModel, Criminal as CriminalModel, Citizen as CitizenModel, CrimeList as CrimeListModel, OB as OBModel
from django.core.files.storage import FileSystemStorage


def PoliceStation(request):
    if request.method == "POST":
        if request.POST.get('statLocation') and request.POST.get('statAddress'):
            policeStation = PoliceStationModel(location=request.POST.get('statLocation'),
                                               address=request.POST.get('statAddress'),
                                               ocsID=request.session['officerID'])
            policeStation.save()
            stationID = policeStation.pk
            currentDate = datetime.now()
            stationNumber = '%s-%s-%s' % (stationID, policeStation.location, currentDate)
            policeStation.stationNumber = stationNumber
            policeStation.save()
            messages.success(request, 'Police Station has been added.')
            return render(request, 'PoliceOfficerApp/addStation.html', {'title': "Police Station"})
    else:
        return render(request, 'PoliceOfficerApp/addStation.html', {'title': "Police Station", 'pageID': 8})


def ViewStations(request):
    station = PoliceStationModel.objects.all()
    return render(request, 'PoliceOfficerApp/viewStations.html', {'title': 'View Police Stations', 'stations': station, 'pageID': 8})


def ShowStation(request, id):
    station = PoliceStationModel.objects.get(id=id)
    return render(request, 'PoliceOfficerApp/showStation.html', {'title': 'Show Station', 'station': station})


def CaseIndex(request):
    ob = OBModel.objects.filter(hasCase=0).all()
    currentStation=request.session['officerStation']
    cases = CaseModel.objects.filter(currentStation=currentStation).all()
    return render(request, 'Case/index.html', {'title': 'Case', 'obs': ob, 'cases': cases, 'pageID': 9})


def ApproveCase(request, id):
    if  request.session['officerRank'] == 'OCS':
        case = CaseModel.objects.get(id=id)
        case.caseStatus = 'APPROVED'
        try:
            case.save()
        except Exception as e:
            messages.error(request, e)
            return redirect('PoliceOfficerApp:CaseIndex')
        else:
            messages.success(request, "Case has been successfully approved.")
            return redirect('PoliceOfficerApp:CaseIndex')
    else:
        messages.error(request, 'You are not authorized to approve cases.')
        return redirect('PoliceOfficerApp:CaseIndex')

def CaseTransfer(request, id):
    case = CaseModel.objects.get(id=id)
    stations = PoliceStationModel.objects.all()
    if request.method == 'POST':
        if request.POST.get('stationID'):
            case.previousStation = case.currentStation
            case.currentStation = request.POST.get('stationID')
            try:
                case.save()
            except Exception as e:
                messages.error(request, e)
                return redirect('PoliceOfficerApp:CaseIndex')
            else:
                messages.success(request, "Case has been successfully transferred.")
                return redirect('PoliceOfficerApp:CaseIndex')
        else:
            messages.error(request, 'An error has occurred. Please contact the administrator.')
            return redirect('PoliceOfficerApp:CaseIndex')
    else:
        return render(request, 'Case/casetransfer.html', {'title': 'Case Transfer', 'case': case, 'stations': stations, 'pageID': 9})


def GenerateCase(request, id):
    case = CaseModel()
    case.officerID = request.session['officerID']
    case.obID = id
    case.caseStatus = 'PENDING'
    case.currentStation = request.session['officerStation']
    ob = OBModel.objects.get(id=id)

    try:
        case.save()
        currentDate = datetime.now()
        case.caseNumber = '%s-%s-%s' % ('CSF', case.pk, currentDate)
        case.save()
        ob.hasCase = case.pk
        ob.save()
    except Exception as e:
        messages.error(request, e)
        return redirect('PoliceOfficerApp:CaseIndex')
    else:
        messages.success(request, 'Case successfully generated.')
        return redirect('PoliceOfficerApp:CaseIndex')


def ViewCase(request, id):
    case = CaseModel.objects.get(id=id)
    ob = OBModel.objects.get(hasCase=case.pk)
    officer = OfficerModel.objects.get(id=ob.officerID)
    citizen = CitizenModel.objects.get(id=ob.citizenID)
    crime = CrimeModel.objects.get(hasOB=ob.pk)
    station = PoliceStationModel.objects.get(id=case.currentStation)
    try:
        criminal = CriminalModel.objects.get(crimeID=crime.pk)
    except Exception as e:
        return render(request, 'Case/viewCase.html', {'title': 'View Case','case':case,'citizen':citizen,'ob':ob,'crime':crime,'officer':officer,'criminal':None,'station':station})
        #return redirect("PoliceOfficerApp:CaseIndex")
    else:
        criminalImages = []
        if criminal.criminalImage is not None:
            for file in json.loads(criminal.criminalImage):
                criminalImages.append(file)
        crimeSceneImages = []
        crimeSceneVideos = []
        if crime.files is not None:
            for file in json.loads(crime.files):
                fileExtension = (file).split(".", 1)[1]
                if fileExtension == 'jpg' or fileExtension == 'jpeg' or fileExtension == 'JPEG' or fileExtension == 'JPG':
                    crimeSceneImages.append(file)
                else:
                    crimeSceneVideos.append(file)
        return render(request, 'Case/viewCase.html', {'title': 'View Case','case':case,'crimeSceneVideos':crimeSceneVideos,'crimeSceneImages':crimeSceneImages,'criminalImages':criminalImages,'citizen':citizen,'ob':ob,'crime':crime,'officer':officer,'criminal':criminal,'station':station})

def addCrimes(request):
    if request.method == 'POST':
        if request.POST.get('crimeName'):
            saverecord = CrimeListModel()
            saverecord.crimeName = request.POST.get('crimeName')
            try:
                saverecord.save()
            except Exception as e:
                messages.error(request, e)
                return render(request, 'PoliceOfficerApp/addCrimes.html')
            else:
                messages.success(request, 'Crime has been added successfully!')
                return render(request, 'PoliceOfficerApp/addCrimes.html')
    else:
        return render(request, 'PoliceOfficerApp/addCrimes.html', {'title': 'Crime Report', 'pageID': 5})


# calls the EditCriminal page and the details of the row you want to CriminalEdit are prefilled
def CriminalEdit(request, id):
    CriminalsDisplay = CriminalModel.objects.get(id=id)
    if request.method == 'POST':
        if request.POST.get('criminalFName') and \
                request.POST.get('criminalLName') and \
                request.POST.get('criminalPhone') and \
                request.POST.get('criminalAddress') and \
                request.POST.get('criminalIDNo') and \
                request.POST.get('criminalGender') and \
                request.POST.get('crimeID') and \
                request.POST.get('criminalStatus') and \
                request.POST.get('arrestLocation') and \
                request.POST.get('arrestDate'):
            CriminalsDisplay.fName = request.POST.get('criminalFName')
            CriminalsDisplay.lName = request.POST.get('criminalLName')
            CriminalsDisplay.tel = request.POST.get('criminalPhone')
            CriminalsDisplay.address = request.POST.get('criminalAddress')
            CriminalsDisplay.nationalID = request.POST.get('criminalIDNo')
            CriminalsDisplay.gender = request.POST.get('criminalGender')
            CriminalsDisplay.crimeID = request.POST.get('crimeID')
            CriminalsDisplay.criminalStatus = request.POST.get('criminalStatus')
            CriminalsDisplay.locationArrested = request.POST.get('arrestLocation')
            CriminalsDisplay.arrestDate = request.POST.get('arrestDate')
            try:
                CriminalsDisplay.save()
            except Exception as e:
                messages.error(request, e)
                return render(request, 'PoliceOfficerApp/EditCriminal.html')
            else:
                messages.success(request, 'Criminal has been updated!')
                return redirect('PoliceOfficerApp:CriminalsDisplay')
        else:
            return render(request, 'PoliceOfficerApp/EditCriminal.html', {'CriminalsDisplay': CriminalsDisplay})
    else:
        return render(request, 'PoliceOfficerApp/EditCriminal.html', {'CriminalsDisplay': CriminalsDisplay})


def obDisplay(request, id):
    CrimesDisplay = CrimeModel.objects.get(id=id)
    if request.method == 'POST':
        if request.POST.get('obAction') and request.POST.get('citizenID') and request.POST.get('crimeID'):
            try:
                filepath = request.FILES['document']
            #This exception handles when there is no file uploaded
            except MultiValueDictKeyError:
                ob = OBModel(citizenID=request.POST.get('citizenID'),
                             crimeID=request.POST.get('crimeID'),
                             reportDate=request.POST.get('reportDate'),
                             actionTaken=request.POST.get('obAction'),
                             officerID=request.session['officerID'])
                try:
                    ob.save()
                    obID = ob.pk
                    obNumber = '%s/%s/%s' % (obID, datetime.now(), request.POST.get('citizenID'))
                    ob.obNo = obNumber

PoliceOfficerApp/templates/PoliceOfficerApp/CrimeListDisplay.html
{% extends "PoliceOfficerApp/base.html" %}
{% block content %}
<h2 class="text-center"> <a href="{% url 'PoliceOfficerApp:CrimeListDisplay' %}"> View Crimes </a> | <a class="text-blue-500" href="{% url 'PoliceOfficerApp:addCrimes' %}"> Add Crimes </a>  </h2>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                  <th scope="col" class="px-6 py-3">
                Crime  ID
                  </th>
            <th scope="col" class="px-6 py-3">
               Crime Name
            </th>
        </tr>
    </thead>
    <tbody>
        {% for CrimeListDisplay in crimelist %}
             <tr class="border-b dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-50 odd:dark:bg-gray-800 even:dark:bg-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">

              <td class="px-6 py-4">
                    {{CrimeListDisplay.crimeID}}
                </td>
                 <td class="px-6 py-4">
                    {{CrimeListDisplay.crimeName}}
                </td>

            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock content %}

PoliceOfficerApp/templates/PoliceOfficerApp/OfficersDisplay.html
{% extends "PoliceOfficerApp/base.html" %}
{% block content %}
<h2 class="text-center"><a href="{% url 'PoliceOfficerApp:OfficersDisplay' %}"> View Officers </a> | <a class="text-blue-500" href="{% url 'PoliceOfficerApp:OfficerRegister' %}"> Register An Officer </a> </h2>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                      Citizen ID
                </th>
            <th>
                First Name
            </th>

                <th scope="col" class="px-6 py-3">
                 Last Name
                </th>
                <th scope="col" class="px-6 py-3">
                    Email
                </th>
 <th scope="col" class="px-6 py-3">
                      Telephone Number
                </th>
 <th scope="col" class="px-6 py-3">
                    National ID
                </th>
 <th scope="col" class="px-6 py-3">
                    Gender
                </th>
 <th scope="col" class="px-6 py-3">
                      Rank
                </th>

       </tr>
        </thead>
        <tbody>
          {% for OfficersDisplay in officers %}
            <tr class="border-b dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-50 odd:dark:bg-gray-800 even:dark:bg-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">

              <td class="px-6 py-4">
                     {{OfficersDisplay.id}}
                </td>
                <td class="px-6 py-4">
                      {{OfficersDisplay.fName}}
                </td>
                <td class="px-6 py-4">
                   {{OfficersDisplay.lName}}
                </td>
<td class="px-6 py-4">
                   {{OfficersDisplay.email}}
                </td>
<td class="px-6 py-4">
                   {{OfficersDisplay.tel}}
                </td>
<td class="px-6 py-4">
                      {{OfficersDisplay.nationalID}}
                </td>
<td class="px-6 py-4">
                    {{OfficersDisplay.gender}}
                </td>
<td class="px-6 py-4">
                   {{OfficersDisplay.rank}}
                </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock content %}

PoliceOfficerApp/templates/PoliceOfficerApp/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <meta name="author" content="David Grzyb">
    <meta name="description" content="">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Tailwind -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" rel="stylesheet">
    <style>
        @import url('https://fonts.googleapis.com/css?family=Karla:400,700&display=swap');
        .font-family-karla { font-family: karla; }
        .bg-sidebar { background: #3d68ff; }
        .cta-btn { color: #3d68ff; }
        .upgrade-btn { background: #1947ee; }
        .upgrade-btn:hover { background: #0038fd; }
        .active-nav-link { background: #1947ee; }
        .nav-item:hover { background: #1947ee; }
        .account-link:hover { background: #3d68ff; }
    </style>
</head>
<body class="bg-gray-100 font-family-karla flex">

    <aside class="relative bg-sidebar h-max w-64 hidden sm:block shadow-xl overflow-y-hidden">
        <div class="p-6">
            <a href="" class="text-white text-3xl font-semibold uppercase hover:text-gray-300">
                {% if 'officerName' in request.session %}
                    {{request.session.officerName}}
                {% endif %}
            </a>
        </div>
        <nav class="text-white text-base font-semibold pt-3">
            <a href="{% url 'PoliceOfficerApp:OfficerDashboard' %}" class="flex items-center {% if pageID == 1 %} active-nav-link {% endif %} text-white py-4 pl-6 nav-item">
                <i class="fas fa-tachometer-alt mr-3"></i>
                Dashboard
            </a>
            <a href="{% url 'PoliceOfficerApp:OfficersDisplay' %}" class="flex items-center {% if pageID == 2 %} active-nav-link {% endif %} text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-sticky-note mr-3"></i>
                Officers
            </a>
            <a href="{% url 'PoliceOfficerApp:CitizensDisplay' %}" class="flex items-center {% if pageID == 3 %} active-nav-link {% endif %} text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-table mr-3"></i>
                Citizen
            </a>
            <a href="{% url 'PoliceOfficerApp:CriminalsDisplay' %}" class="flex items-center {% if pageID == 4 %} active-nav-link {% endif %} text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-table mr-3"></i>
                Criminals
            </a>
            <a href="{% url 'PoliceOfficerApp:CrimeListDisplay' %}" class="flex items-center {% if pageID == 5 %} active-nav-link {% endif %} text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-table mr-3"></i>
                Crimes
            </a>
            <a href="{% url 'PoliceOfficerApp:CrimesDisplay' %}" class="flex items-center {% if pageID == 6 %} active-nav-link {% endif %} text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-table mr-3"></i>
                Record OB
            </a>
            <a href="{% url 'PoliceOfficerApp:ViewStations' %}" class="flex items-center {% if pageID == 8 %} active-nav-link {% endif %} text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-table mr-3"></i>
                Police Station
            </a>
            <a href="{% url 'PoliceOfficerApp:CaseIndex' %}" class="flex items-center {% if pageID == 9 %} active-nav-link {% endif %} text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-table mr-3"></i>
                Case
            </a>
            <a href="{% url 'PoliceOfficerApp:OfficerProfile' %}" class="flex items-center {% if pageID == 7 %} active-nav-link {% endif %} text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-table mr-3"></i>
                Profile
            </a>

        </nav>
        <a href="{% url 'PoliceOfficerApp:OfficerLogout' %}" class="absolute w-full h-10 upgrade-btn bottom-0 active-nav-link text-white flex items-center justify-center py-4">
            Logout
        </a>
    </aside>

    <div class="w-full flex flex-col h-screen overflow-y-hidden">
        <div class="overflow-y-auto select-none p-4 h-full">
            {% if messages %}
                {% for message in messages%}
                    {% if message.tags == 'error' %}
                        <div class="flex justify-center">
                            <div class="p-4 m-4 bg-red-300 w-2/3 text-red-800 rounded border-red-600 border-2">
                                <span>
                                    {{message}}
                                </span>
                            </div>
                        </div>
                    {% else %}
                        <div class="flex justify-center">
                            <div class="p-4 m-4 bg-green-300 w-2/3 text-green-800 rounded border-green-600 border-2">
                                <span>
                                    {{message}}
                                </span>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif%}
            {% block content %}
                <!-- body of the page you have selected -->
            {% endblock %}
        </div>

        <!-- AlpineJS -->
    </div>
</body>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>


<script src="{% static 'js/helpers.js' %}"></script>
<script src="{% static 'js/validation.js' %}"></script>
<script>
    if ($("#officer-form")) {
         var fname_is_valid = false, lname_is_valid = false, address_is_valid = false, email_is_valid = false,
              phone_is_valid = false;

         $("#OFName").keyup(function () {
             if (validateText($("#OFName"), $("#OFNameError"))) {
                 fname_is_valid = true;
             } else {
                 fname_is_valid = false;
             }

         });

         $("#OLName").keyup(function () {
             if (validateText($("#OLName"), $("#OLNameError"))) {
                 lname_is_valid = true;
             } else {
                 lname_is_valid = false;
             }

         });

         $("#OAddress").keyup(function () {
                if (validateText($("#OAddress"), $("#OAddressError"))) {
                    address_is_valid = true;
                } else {
                    address_is_valid = false;
                }
        });
            $("#OPhone").keyup(function () {
                if (validateTel($("#OPhone"), $("#OPhoneError"))) {
                    phone_is_valid = true;
                } else {
                    phone_is_valid = false;
                }
        });
        $("#OEmail").keyup(function () {
            if (validateEmail($("#OEmail"), $("#OEmailError"))) {
                email_is_valid = true;
            } else {
                email_is_valid = false;
            }
            });



        $("#OBtn").click(function (e) {
            e.preventDefault();
            if (fname_is_valid == true && lname_is_valid == true && address_is_valid == true && email_is_valid == true) {
                $('#officer-form').submit()
            }
        });
        }
</script>
</html>

PoliceOfficerApp/templates/PoliceOfficerApp/index.html
{% extends "PoliceOfficerApp/base.html" %}
{% block content %}
    <div class="w-full overflow-x-hidden border-t flex flex-col">
        <main class="w-full flex-grow p-6">
            <h1 class="text-3xl text-black pb-6">
                Welcome {{request.session.officerName}} to the Officer Dashboard
            </h1>
            <span class="text xl">
                What would you like to do now?
            </span>
        </main>
    </div>
{% endblock content %}

PoliceOfficerApp/templates/PoliceOfficerApp/viewStations.html
{% extends "PoliceOfficerApp/base.html" %}
{% block content %}
<div class="flex justify-center w-full my-4">
    <h2 class="flex flex-row">
        <div>
            <a class="text-blue-500" href="{% url 'PoliceOfficerApp:ViewStations' %}">
                View Police Stations
            </a>
        </div>
        <div class="px-4">
            <span>
                |
            </span>
        </div>
        <div>
            <a class="text-blue-500" href="{% url 'PoliceOfficerApp:PoliceStation' %}">
                Add Police Station
            </a>
        </div>
    </h2>
</div>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Station ID
                </th>
                <th scope="col" class="px-6 py-3">
                    Station Location
                </th>
                <th scope="col" class="px-6 py-3">
                    Officer Count
                </th>
                <th scope="col" class="px-6 py-3">
                    Address
                </th>
                <th scope="col" class="px-6 py-3">
                    Station Number
                </th>
                <th scope="col" class="px-6 py-3">
                    OCS Name
                </th>
                <th scope="col" class="px-6 py-3">
                    Action
                </th>
        </tr>
    </thead>
    <tbody>
        {% for station in stations %}
             <tr class="border-b dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-50 odd:dark:bg-gray-800 even:dark:bg-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">

              <td class="px-6 py-4">
                    {{station.id}}
                </td>
                 <td class="px-6 py-4">
                    {{station.location}}
                </td>
                   <td class="px-6 py-4">
                    {{station.officersCount}}
                </td>
                   <td class="px-6 py-4">
                    {{station.address}}
                </td>
                </td>
                 <td class="px-6 py-4">
                    {{station.stationNumber}}
                 </td>
                 </td>
                 <td class="px-6 py-4">
                    {{request.session.officerName}}
                </td>
                 <td class="px-6 py-4">
                     <a href="{% url 'PoliceOfficerApp:ShowStation' station.id%}" class="text-blue-500 underline">
                         View
                     </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock content %}