CitizenApp/urls.py
from django.urls import path, include
from . import views as citizen_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'CitizenApp'
urlpatterns = [
    path('profile/', citizen_views.CitizenProfile, name='CitizenProfile'),
    path('login/', citizen_views.CitizenLogin, name='CitizenLogin'),
    path('logout/', citizen_views.CitizenLogout, name='CitizenLogout'),
    path('EditCitizen/<int:id>', citizen_views.CitizenEdit, name='CitizenEdit'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, name='uploads')

police_system/urls.py
from django.contrib import admin
from django.urls import path, include
from records import views as record_views
from django.conf import settings
from django.conf.urls.static import static

app_name='PoliceSystem'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('evidence/',record_views.evidence, name='evidence'),
    path('crimereport/', record_views.CrimeListDisplay, name='crimereport'),
    path('issueforms/', record_views.issueforms, name='issueforms'),
    path('signup/',record_views.signup, name='userSignUp'),
    path('',record_views.landingpage, name='index'),
    path('citizen/', include('CitizenApp.urls'), name='citizen'),
    path('policeofficer/', include('PoliceOfficerApp.urls'), name='policeofficer')
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

CitizenApp/views.py
from django.contrib import messages
from django.contrib.auth.hashers import check_password
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.utils.datastructures import MultiValueDictKeyError

from records.views import landingpage
from records.models import Citizen as CitizenModel


def CitizenProfile(request):
    if 'citizenID' in request.session:
        citizen = CitizenModel.objects.get(id=request.session['citizenID'])
        return render(request, 'CitizenApp/citizenProfile.html', {'citizen': citizen})
    else:
        return redirect('CitizenApp:CitizenLogin')


def CitizenLogin(request):
    if request.method == "POST":
        if request.POST.get('loginEmail') and request.POST.get('loginPassword'):
            loginEmail = request.POST.get('loginEmail')
            loginPassword = request.POST.get('loginPassword')
            try:
                citizen = CitizenModel.objects.get(email=loginEmail)

                if check_password(loginPassword, citizen.password):
                    # TODO create single variable that stores individual column of the citizen table.
                    request.session['citizenID'] = citizen.id
                    request.session['citizenName'] = citizen.fName + ' ' + citizen.lName
                    request.session['citizenImage'] = citizen.citizenImage.url

                    # currentCitizen = CitizenClass(citizen.id,citizen.fName,citizen.lName,citizen.email,citizen.tel,citizen.password,citizen.nationalID,citizen.gender,citizen.address)

                    # return render(request, 'records/CitizenLogin.html')
                    return redirect(landingpage)
                else:
                    messages.error(request, 'Invalid Password.Please Try Again...')
                    return render(request, 'records/CitizenLogin.html', {'title': 'Login'})
            except Exception as e:
                messages.error(request, 'Invalid Password.Please Try Again...')
                return render(request, 'records/CitizenLogin.html', {'title': 'Login'})
    else:
        return render(request, 'records/CitizenLogin.html', {'title': 'Login'})


def CitizenLogout(request):
    try:
        del request.session['citizenID']
    except Exception as e:
        messages.error(request, e)
    else:
        messages.success(request, 'Logged out.')
        return redirect('/', {'title': 'Landing Page', 'pageId': 8})


def CitizenEdit(request, id):
    if 'citizenID' in request.session:
        citizen = CitizenModel.objects.get(id=id)
        if request.method == 'POST':
            if request.POST.get('regEmail') and \
                    request.POST.get('regPhone') and \
                    request.POST.get('regAddress'):
                citizen.email = request.POST.get('regEmail')
                citizen.tel = request.POST.get('regPhone')
                citizen.address = request.POST.get('regAddress')

                try:
                    citizenImage = request.FILES['citizenImage']
                except MultiValueDictKeyError as e:
                    citizen.save()
                    return redirect('CitizenApp:CitizenProfile')
                except Exception as e:
                    messages.error(request, e)
                    return render(request, 'CitizenApp/EditCitizen.html')
                else:
                    fileStorage = FileSystemStorage()
                    citizenImageName = 'citizen-%s%s' % (citizen.id, '.jpg')
                    fileStorage.save('%s' % citizenImageName, citizenImage)
                    citizen.citizenImage = fileStorage.save('%s' % citizenImageName, citizenImage)
                    citizen.save()
                    request.session['citizenImage'] = citizen.citizenImage.url
                    messages.success(request, 'citizen details successfully updated.')
                    return redirect('CitizenApp:CitizenProfile')
            else:
                messages.error(request, 'An error has occurred. Please contact an administrator.')
                return render(request, 'CitizenApp/EditCitizen.html', {'title': 'citizen Edit', 'citizen': citizen})
        else:
            return render(request, 'CitizenApp/EditCitizen.html', {'title': 'Citizen Edit', 'citizen': citizen})
    else:
        return redirect('CitizenApp:CitizenLogin')

CitizenApp/templates/CitizenApp/EditCitizen.html
{% extends "records/base.html" %}
{% block content %}

<div class="flex justify-center">
        <div class="my-2 mx-10 w-full rounded-lg flex flex-row">
                <div class="w-full p-4 bg-gray-100 rounded-l-lg">
                    <div class="form-container w-full m-auto flex flex-col justify-center my-2">
                        <div class="flex flex-col my-4">
                            <div class="flex flex-col">
                                <span class="text-4xl">
                                    Update your details
                                </span>
                            </div>
                        </div>
                        <hr class="text-black border-2 border-black my-4">
                        <form action="" method="POST" class="flex flex-col" enctype="multipart/form-data" autocomplete="off">
                            {% csrf_token %}
                            <div class="flex flex-row justify-around">
                                <div class="flex flex-col w-full w-5/12">
                                <div class="form-group w-full flex flex-row my-2 justify-between">
                                <div class="w-1/2 mr-2 ">
                                    <div class="form-label">
                                        <label for="regFName" class="text-base my-2">
                                            First Name
                                        </label>
                                    </div>
                                    <div class="form-input my-2 flex">
                                        <input type="text" id="regFName" value="{{citizen.fName}}" disabled name="regFName" class="bg-gray-200 select-none cursor-not-allowed w-full p-2 rounded hover:border-blue border-2">
                                    </div>
                                    <div class="text-xs">
                                        <span class="text-gray-700">
                                            John
                                        </span>
                                    </div>
                                </div>
                                <div class="ml-2 w-1/2">
                                    <div class="form-label">
                                        <label for="regLName" class="text-base my-2">
                                            Last Name
                                        </label>
                                    </div>
                                    <div class="form-input my-2 flex">
                                        <input type="text" id="regLName" value="{{citizen.lName}}" disabled name="regLName" class="bg-gray-200 select-none cursor-not-allowed w-full p-2 rounded hover:border-blue border-2">
                                    </div>
                                    <div class="text-xs">
                                        <span class="text-gray-700">
                                            Doe
                                        </span>
                                    </div>
                                </div>
                            </div>
                                <div class="form-group w-full flex flex-row my-2 justify-between">
                                    <div class="w-1/2 mr-2 ">
                                        <div class="form-label">
                                            <label for="regPhone" class="text-base my-2">
                                                Telephone
                                            </label>
                                        </div>
                                        <div class="form-input my-2 flex">
                                            <input type="text" id="regPhone" value="{{citizen.tel}}" name="regPhone" class="w-full p-2 rounded hover:border-blue invalid:border-red-500 valid:border-green-500 required:border-red-500 border-2">
                                        </div>
                                        <div class="text-xs">
                                            <span class="text-gray-700">
                                                +254|
                                            </span>
                                        </div>
                                    </div>
                                    <div class="ml-2 w-1/2">
                                        <div class="form-label">
                                            <label for="regAddress" class="text-base my-2">
                                                Address
                                            </label>
                                        </div>
                                        <div class="form-input my-2 flex">
                                            <input type="text" id="regAddress" value="{{citizen.address}}" name="regAddress" class="w-full p-2 rounded hover:border-blue invalid:border-red-500 valid:border-green-500 required:border-red-500 border-2">
                                        </div>
                                        <div class="text-xs">
                                            <span class="text-gray-700">
                                                Embakasi, Nairobi
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group w-full flex flex-col my-2">
                                    <div class="form-label">
                                        <label for="regIDNo" class="text-base my-2">
                                            National ID/Passport/Birth Certificate Number
                                        </label>
                                    </div>
                                    <div class="form-input my-2">
                                        <input type="text" id="regIDNo" value="{{citizen.nationalID}}" name="regIDNo" disabled minlength="4" class="bg-gray-200 select-none cursor-not-allowed w-full p-2 rounded hover:border-blue border-2">
                                    </div>
                                    <div class="text-xs">
                                        <span class="text-gray-700">

                                        </span>
                                    </div>
                                </div>
                                <div class="form-group w-full flex flex-col my-2">
                                    <div class="form-label">
                                        <label for="regGender" class="text-base my-2">
                                            Gender
                                        </label>
                                    </div>
                                    <div class="form-input my-2">
                                        <select name="regGender" id="regGender" disabled class="bg-gray-200 select-none cursor-not-allowed w-full p-2 rounded hover:border-blue border-2">
                                            <option value="{{citizen.gender}}">{{citizen.gender}}</option>
                                            <option value="male">Male</option>
                                            <option value="female">Female</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                                <div class="flex flex-col w-full w-5/12">
                                <div class="form-group w-full flex flex-col my-2">
                                    <div class="form-label">
                                        <label for="regEmail" class="text-base my-2">
                                            Email
                                        </label>
                                    </div>
                                    <div class="form-input my-2 flex">
                                        <input type="email" id="regEmail" autocomplete="off" value="{{citizen.email}}" name="regEmail" class="w-full p-2 rounded hover:border-blue invalid:border-red-500 valid:border-green-500 required:border-red-500 border-2">
                                    </div>
                                </div>
                                <div class="form-group w-full flex flex-col my-2">
                                <div class="form-label">
                                    <label for="oldPassword" class="text-base my-2">
                                        Old Password
                                    </label>
                                </div>
                                <div class="form-input my-2">
                                    <input type="password" id="oldPassword" autocomplete="off" value="" name="oldPassword" minlength="4" class="w-full p-2 rounded hover:border-blue invalid:border-red-500 valid:border-green-500 required:border-red-500 border-2">
                                </div>
                                <div class="text-xs">
                                    <span class="text-gray-700">
                                        Enter your old password.
                                    </span>
                                </div>
                            </div>
                                <div class="form-group w-full flex flex-col my-2">
                                    <div class="form-label">
                                        <label for="newPassword" class="text-base my-2">
                                            New Password
                                        </label>
                                    </div>
                                    <div class="form-input my-2">
                                        <input type="password" id="newPassword" name="newPassword" minlength="4" class="w-full p-2 rounded hover:border-blue invalid:border-red-500 valid:border-green-500 required:border-red-500 border-2">
                                    </div>
                                    <div class="text-xs">
                                        <span class="text-gray-700">
                                            Enter new password.
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group w-full flex flex-col my-2">
                                    <div class="form-label">
                                        <label for="citizenImage" class="text-base my-2">
                                            Profile Photo
                                        </label>
                                    </div>
                                    <div class="form-input my-2">
                                        <input type="file" id="citizenImage" name="citizenImage" minlength="4" class="w-full p-2 rounded hover:border-blue invalid:border-red-500 valid:border-green-500 required:border-red-500 border-2">
                                    </div>
                                    <div class="text-xs">
                                        <span class="text-gray-700">
                                            Choose a profile photo
                                        </span>
                                    </div>
                                </div>
                            </div>
                            </div>
                            <div class="form-button w-full flex justify-center my-4">
                                <button class="p-2 text-center w-1/2 rounded bg-blue-600 text-white text-lg">
                                    Update details
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
    </div>

{% endblock content %}

CitizenApp/templates/CitizenApp/citizenProfile.html
{% extends "records/base.html" %}
{% block content %}
<div class="main-container flex flex-row w-full p-2 h-screen">
    <div class="flex flex-col p-2 w-1/4 mr-1 bg-gray-100 rounded-l-lg">
        <div class="profile-image p-1">
            <img src="{{citizen.citizenImage.url}}" alt="">
        </div>
        <div class="profile-details p-1 flex flex-col w-full">
            <div class="w-full">
                <span class="text-2xl font-bold">
                    {{request.session.citizenName}}
                </span>
            </div>
            <div class="w-full">
                <span class="text-lg">
                    Citizen
                </span>
            </div>
            <div class="w-full text-gray-500 hover:text-black transition-all">
                <span class="text-base">
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam assumenda, dolorem eaque earum eveniet exercitationem illum ipsa, iste minima, nihil numquam officiis perferendis ratione sapiente soluta totam velit voluptates.
                </span>
            </div>
            <div class="personal-detail-group flex flex-row justify-between my-2 items-center">
                        <span class="">
                            Account Status
                        </span>
                        {% if citizen.accountStatus == 0 %}
                            <span class="text-white p-2 rounded bg-green-500">
                                Active
                            </span>
                        {% else %}
                            <span class="text-white p-2 rounded bg-red-500">
                                Inactive
                            </span>
                        {% endif %}
                    </div>
            <hr>
            <div class="personal-detail-group flex flex-row justify-between my-2">
                <span class="">
                    Join Date
                </span>
                <span class="text-gray-700">
                    {{citizen.joinDate}}
                </span>
            </div>
        </div>
    </div>
    <div class="flex flex-col w-3/4 ml-1">
        <div class="w-full bg-gray-100 h-1/2 mb-1 rounded-tr-lg flex flex-col personal-details p-2">
            <div class="flex flex-row justify-between">
                <div class="header flex flex-row items-center">
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-7" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd" />
                        </svg>
                    </div>
                    <div class="flex items-center">
                        <span class="text-xl text-bold">
                            Personal details.
                        </span>
                    </div>
                </div>
                <div>
                    <a href="{% url 'CitizenApp:CitizenEdit' citizen.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-7" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                        </svg>
                    </a>
                </div>
            </div>
            <div class="main-body flex flex-row my-3 gap-x-32">
                <div class="flex-col w-1/3">
                    <div class="personal-detail-group flex flex-row justify-between my-3">
                        <span class="">
                            First Name
                        </span>
                        <span class="text-gray-700">
                            {{citizen.fName}}
                        </span>
                    </div>
                    <div class="personal-detail-group flex flex-row justify-between my-3">
                        <span class="">
                            Last Name
                        </span>
                        <span class="text-gray-700">
                            {{citizen.lName}}
                        </span>
                    </div>
                    <div class="personal-detail-group flex flex-row justify-between my-3">
                        <span class="">
                            Email
                        </span>
                        <span class="text-gray-700">
                            {{citizen.email}}
                        </span>
                    </div>
                    <div class="personal-detail-group flex flex-row justify-between my-3">
                        <span class="">
                            Address
                        </span>
                        <span class="text-gray-700">
                            {{citizen.address}}
                        </span>
                    </div>
                </div>
                <div class="flex-col w-1/3">
                    <div class="personal-detail-group flex flex-row justify-between my-3">
                        <span class="">
                            Mobile
                        </span>
                        <span class="text-gray-700">
                            {{citizen.tel}}
                        </span>
                    </div>
                    <div class="personal-detail-group flex flex-row justify-between my-3">
                        <span class="">
                            National ID
                        </span>
                        <span class="text-gray-700">
                            {{citizen.nationalID}}
                        </span>
                    </div>
                    <div class="personal-detail-group flex flex-row justify-between my-3">
                        <span class="">
                            Gender
                        </span>
                        <span class="text-gray-700">
                            {{citizen.gender}}
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-full bg-gray-100 h-1/2 mt-1 rounded-br-lg w-full flex flex-row gap-x-20 p-2">
            <div class="flex flex-col">
                <div>
                    <span>
                        Metrics
                    </span>
                </div>
                <div>
                    <span>
                        Cases reported: 20
                    </span>
                </div>
            </div>
            <div>
                <div class="flex flex-col">
                    <div>
                        <span>
                            Metrics
                        </span>
                    </div>
                    <div>
                        <span>
                            OBs issued: 4
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}