CitizenApp/urls.py
from django.urls import path, include
from . import views as citizen_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'CitizenApp'
urlpatterns = [
    path('profile/', citizen_views.CitizenProfile, name='CitizenProfile'),
    path('login/', citizen_views.CitizenLogin, name='CitizenLogin'),
    path('logout/', citizen_views.CitizenLogout, name='CitizenLogout'),
    path('EditCitizen/<int:id>', citizen_views.CitizenEdit, name='CitizenEdit'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, name='uploads')

PoliceOfficerApp/urls.py
from django.urls import path, include
from . import views as officer_views
from django.conf import settings
from django.conf.urls.static import static

app_name = "PoliceOfficerApp"
urlpatterns = [
    path('', officer_views.index, name='OfficerDashboard'),
    path('OfficersDisplay/', officer_views.OfficersDisplay, name='OfficersDisplay'),
    path('OfficerProfile/', officer_views.OfficerProfile, name='OfficerProfile'),
    path('CitizensDisplay/', officer_views.CitizensDisplay, name='CitizensDisplay'),
    path('CrimesDisplay/', officer_views.CrimesDisplay, name='CrimesDisplay'),
    path('criminalbooking/', officer_views.criminalbooking, name='criminalbooking'),
    path('CriminalsDisplay/', officer_views.CriminalsDisplay, name='CriminalsDisplay'),
    path('CrimeListDisplay/', officer_views.CrimeListDisplay, name='CrimeListDisplay'),
    path('PoliceStation/', officer_views.PoliceStation, name='PoliceStation'),
    path('ViewStations/', officer_views.ViewStations, name='ViewStations'),
    path('login/', officer_views.login, name='OfficerLogin'),
    path('addCrimes/', officer_views.addCrimes, name='addCrimes'),

    path('case/', officer_views.CaseIndex, name='CaseIndex'),

    path('casetransfer/<int:id>', officer_views.CaseTransfer, name='CaseTransfer'),
    path('ob/<int:id>', officer_views.obDisplay, name='ob'),
    path('viewCase/<int:id>', officer_views.ViewCase, name='ViewCase'),
    path('approveCase/<int:id>', officer_views.ApproveCase, name='ApproveCase'),
    path('viewOB/<int:id>', officer_views.ViewOB, name='ViewOB'),
    path('showStation/<int:id>', officer_views.ShowStation, name='ShowStation'),
    path('generateCase/<int:id>', officer_views.GenerateCase, name='GenerateCase'),
    # CriminalEdit and update paths
    path('EditCriminal/<int:id>', officer_views.CriminalEdit, name='CriminalEdit'),
    path('EditOfficer/<int:id>', officer_views.OfficerEdit, name='OfficerEdit'),

    path('OfficerRegister/', officer_views.OfficerRegister, name='OfficerRegister'),
    path('logout/', officer_views.OfficerLogout, name='OfficerLogout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

police_system/urls.py
from django.contrib import admin
from django.urls import path, include
from records import views as record_views
from django.conf import settings
from django.conf.urls.static import static

app_name='PoliceSystem'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('evidence/',record_views.evidence, name='evidence'),
    path('crimereport/', record_views.CrimeListDisplay, name='crimereport'),
    path('issueforms/', record_views.issueforms, name='issueforms'),
    path('signup/',record_views.signup, name='userSignUp'),
    path('',record_views.landingpage, name='index'),
    path('citizen/', include('CitizenApp.urls'), name='citizen'),
    path('policeofficer/', include('PoliceOfficerApp.urls'), name='policeofficer')
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

records/models.py
import json

from django.db import models


class OB(models.Model):
    citizenID = models.IntegerField()
    crimeID = models.IntegerField()
    obNo = models.CharField(max_length=30)
    reportDate = models.DateTimeField()
    actionTaken = models.CharField(max_length=200)
    file = models.JSONField()
    officerID = models.IntegerField()
    createDate = models.DateTimeField(auto_now_add=True)
    hasCase = models.IntegerField(default=0)

    class Meta:
        db_table = "tbl_ob"


class Case(models.Model):
    officerID = models.IntegerField()
    caseNumber = models.CharField(max_length=40)
    caseStatus = models.CharField(max_length=30)
    obID = models.IntegerField()
    generateDate = models.DateTimeField(auto_now_add=True)
    previousStation = models.IntegerField()
    currentStation = models.IntegerField()

    class Meta:
        db_table = "tbl_case"


class PoliceStation(models.Model):
    location = models.CharField(max_length=100)
    officersCount = models.IntegerField(default=0)
    address = models.CharField(max_length=100)
    ocsID = models.IntegerField()
    stationNumber = models.CharField(max_length=100)
    stationStatus = models.BooleanField(default=False)
    establishDate = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'tbl_station'


class Evidence(models.Model):
    description = models.CharField(max_length=400)
    Form=models.ImageField()

    class Meta:
        db_table = "tbl_evidence"


class CrimeList(models.Model):
    crimeID = models.AutoField(auto_created=True, primary_key=True)
    crimeName = models.TextField(max_length=400)

    class Meta:
        db_table = "tbl_crimelist"


class Crime(models.Model):
    description = models.CharField(max_length=400)
    crimeID = models.IntegerField()
    citizenID = models.IntegerField()
    reportTime = models.DateTimeField(auto_now_add=True)
    files = models.JSONField()
    hasOB = models.IntegerField()

    class Meta:
        db_table = "tbl_crime_report"


class CrimeAnonymous(models.Model):
    description = models.CharField(max_length=400)
    crimeID = models.IntegerField()
    reportTime = models.DateTimeField(auto_now_add=True)
    files = models.JSONField()
    hasOB = models.BooleanField(default=False)

    class Meta:
        db_table = "tbl_crime_report_anonymous"


class Citizen(models.Model):
    fName = models.CharField(max_length=100)
    lName = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    tel = models.CharField(max_length=100)
    password = models.CharField(max_length=400)
    nationalID = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    citizenImage = models.ImageField()
    joinDate = models.DateTimeField(auto_now=True)
    accountStatus = models.BooleanField(default=False)

    class Meta:
        db_table = "tbl_citizen"


class Criminal(models.Model):
    fName = models.CharField(max_length=100)
    lName = models.CharField(max_length=100)
    tel = models.CharField(max_length=100)
    address = models.CharField(max_length=400)
    nationalID = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    crimeID = models.IntegerField()
    criminalImage = models.JSONField()
    criminalStatus = models.CharField(max_length=100)
    locationArrest = models.CharField(max_length=100)
    arrestDate = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "tbl_criminal"


class Officer(models.Model):
    fName = models.CharField(max_length=100)
    lName = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    tel = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    nationalID = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    rank = models.CharField(max_length=100)
    password = models.CharField(max_length=400)
    employmentStatus = models.BooleanField(default=False)
    employmentDate = models.DateTimeField(auto_now_add=True)
    stationID = models.IntegerField()

    class Meta:
        db_table = "tbl_police_officer"

records/views.py
import json

from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.core.files.storage import FileSystemStorage
from django.db import IntegrityError
from django.shortcuts import redirect
from django.utils.datastructures import MultiValueDictKeyError

from records.models import Citizen as CitizenModel, CrimeList as CrimeListModel, Crime as CrimeModel, \
    CrimeAnonymous as CrimeAnonymousModel, Evidence as EvidenceModel, Case as CaseModel
from django.shortcuts import render



def evidence(request):
    context = {}
    if request.method == 'POST':
       if   request.FILES['Form']  and request.POST.get('description') :

           fileStorage = FileSystemStorage()
           Form = request.FILES['Form']
           saverecord = EvidenceModel()
           saverecord.description = request.POST.get('description')

           try:
               saverecord.save()
               id = saverecord.pk
               name = 'form-%s%s' % (id, '.pdf')

               display = fileStorage.save('%s' % name, Form)
               context['url']=fileStorage.url(display)

               saverecord.Form = name
               saverecord.save()
           except IntegrityError as e:
               messages.error(request, 'Upload Not Successful...')
               return render(request, 'records/evidence.html',context)
           else:
               messages.success(request, 'Evidence Uploaded Successfully...!')
               return render(request, 'records/evidence.html', context)
       else:
           messages.error(request, 'Upload Not Successful...')
           return render(request, 'records/evidence.html',context)
    else:
           return render(request, 'records/evidence.html', context)


def CrimeListDisplay(request):
    crimelist = CrimeListModel.objects.all()
    global filesList, uploadedFiles
    filesList = []
    uploadedFiles = None
    if request.method == 'POST':
        if request.POST.get('crimeID') and request.POST.get('crimeDescription'):
            # Here we check if a citizen is logged in so that we can decide whether the crime has been reported anonymously or not.
            if 'citizenID' in request.session:
                if request.POST.get('anonymous'):
                    crimeAnonymous = CrimeAnonymousModel()
                    crimeAnonymous.crimeID = CrimeListModel.objects.get(crimeID=request.POST.get('crimeID')).pk
                    crimeAnonymous.description = request.POST.get('crimeDescription')
                    try:
                        crimeAnonymous.save()
                        fileStorage = FileSystemStorage()
                        counter = 0
                        for file in request.FILES.getlist('crimeFiles'):
                            fileExtension = file.name.split(".", 1)[1]
                            uploadedFileName = 'CRA-%s-%d.%s' % (crimeAnonymous.pk, counter, fileExtension)
                            fileStorage.save('%s' % uploadedFileName, file)
                            filesList.append(uploadedFileName)
                            counter += 1
                        jsonList = json.dumps(filesList)
                        crimeAnonymous.files = jsonList
                        crimeAnonymous.save()
                    except Exception as e:
                        messages.error(request, e)
                        return render(request, "records/crimereport.html", {"crimelists": crimelist})
                    else:
                        messages.success(request, 'Crime has been reported successfully!')
                        return render(request, "records/crimereport.html",
                                      {'title': 'Report Crime Portal', "crimelists": crimelist})
                else:
                    crime = CrimeModel()
                    crime.crimeID = CrimeListModel.objects.get(crimeID=request.POST.get('crimeID')).pk
                    crime.description = request.POST.get('crimeDescription')
                    crime.citizenID = request.session['citizenID']
                    crime.hasOB = 0
                    try:
                        crime.save()
                        fileStorage = FileSystemStorage()
                        counter = 0
                        for file in request.FILES.getlist('crimeFiles'):
                            fileExtension = file.name.split(".", 1)[1]
                            uploadedFileName = 'CRA-%s-%d.%s' % (crime.pk, counter, fileExtension)
                            fileStorage.save('%s' % uploadedFileName, file)
                            filesList.append(uploadedFileName)
                            counter += 1
                        jsonList = json.dumps(filesList)
                        crime.files = jsonList
                        crime.save()
                    except Exception as e:
                        messages.error(request, e)
                        return render(request, "records/crimereport.html", {"crimelists": crimelist})
                    else:
                        messages.success(request, 'Crime has been reported successfully!')
                        return render(request, "records/crimereport.html",
                                      {'title': 'Report Crime Portal', "crimelists": crimelist})
            else:
                crimeAnonymous = CrimeAnonymousModel()
                crimeAnonymous.crimeID = CrimeListModel.objects.get(crimeID=request.POST.get('crimeID')).pk
                crimeAnonymous.description = request.POST.get('crimeDescription')
                try:
                    crimeAnonymous.save()
                    fileStorage = FileSystemStorage()
                    counter = 0
                    for file in request.FILES.getlist('crimeFiles'):
                        fileExtension = file.name.split(".", 1)[1]
                        uploadedFileName = 'CRA-%s-%d.%s' % (crimeAnonymous.pk, counter , fileExtension)
                        fileStorage.save('%s' % uploadedFileName, file)
                        filesList.append(uploadedFileName)
                        counter +=1
                    jsonList = json.dumps(filesList)
                    crimeAnonymous.files = jsonList
                    crimeAnonymous.save()
                except Exception as e:
                    messages.error(request, e)
                    return render(request, "records/crimereport.html", {"crimelists": crimelist})
                else:
                    messages.success(request, 'Crime has been reported successfully!')
                    return render(request, "records/crimereport.html",
                                  {'title': 'Report Crime Portal', "crimelists": crimelist})
        else:
            messages.error(request, 'An error has occurred')
            return render(request, "records/crimereport.html", {'title': 'Report Crime Portal',"crimelists": crimelist})
    else:
        return render(request, "records/crimereport.html", {'title': 'Report Crime Portal',"crimelists": crimelist})


def issueforms(request):
    return render(request, 'records/issueforms.html', {'title': 'Issue Forms '})


def signup(request):
    if request.method == 'POST':
        if request.POST.get('regFName') and \
                request.POST.get('regLName') and \
                request.POST.get('regEmail') and \
                request.POST.get('regPhone') and \
                request.POST.get('regPassword') and \
                request.POST.get('regConPassword') and \
                request.POST.get('regIDNo') and \
                request.POST.get('regGender') and \
                request.FILES['citizenImage'] and \
                request.POST.get('regAddress'):
            # If the password and confirm password are same then the data will be saved in the database else an error message will be sent
            if request.POST.get('regPassword') == request.POST.get('regConPassword'):
                # Getting the image that has been uploaded
                fileStorage = FileSystemStorage()
                citizenImage = request.FILES['citizenImage']

                saverecord = CitizenModel()
                saverecord.fName = request.POST.get('regFName')
                saverecord.lName = request.POST.get('regLName')
                saverecord.email = request.POST.get('regEmail')
                saverecord.tel = request.POST.get('regPhone')

                # Hash password before recording in the DB
                saverecord.password = make_password(request.POST.get('regPassword'))
                saverecord.nationalID = request.POST.get('regIDNo')
                saverecord.gender = request.POST.get('regGender')
                saverecord.address = request.POST.get('regAddress')
                try:
                    saverecord.save()
                    citizenID = saverecord.pk
                    citizenImageName = 'citizen-%s%s' % (citizenID, '.jpg')
                    fileStorage.save('%s' % citizenImageName, citizenImage)
                    saverecord.citizenImage = citizenImageName
                    saverecord.save()
                except IntegrityError as e:
                    messages.error(request, e)
                    return render(request, 'records/signup.html')
                else:
                    messages.success(request, 'Record Saved Successfully...!')
                    return redirect('CitizenApp:CitizenLogin')
            else:
                messages.error(request, 'Passwords do not match.')
                return render(request, 'records/signup.html')
    else:
        return render(request, 'records/signup.html', {'title': 'Sign Up'})


def dashboard(request):
    return render(request, 'records/dashboard.html', {'title': 'Dashboard'})


def landingpage(request):
    return render(request, 'records/index.html', {'title': 'Landing Page', 'pageId': 8})

records/templates/records/base.html
{% load static %}

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="">
    <header class="navbar w-full relative">
        <nav class="{% if 8 == pageId %} '{{pageId}}' absolute top-0 text-white {% endif %} flex flex-row w-full p-2 justify-between items-center z-10">
            <div class="nav-brand w-1/4">
                <img src="{% static 'media/policeLogo.png' %}" alt="Navbar brand">
            </div>
            <div class="nav-main w-3/4 mx-4 flex flex-row-reverse md:flex-row md:justify-around items-center">
                <div class="nav-links w-full hidden md:contents flex flex-row justify-around items-center">
                    <div class="nav-link">
                        <a href="{% url 'index' %}">
                            <span class="text-xl">
                                Home
                            </span>
                        </a>
                    </div>
                    {% if 'citizenID' not in request.session %}
                    <div class="nav-link">
                        <a href="{% url 'userSignUp' %}">
                            <span class="text-xl">
                                Sign Up
                            </span>
                        </a>
                    </div>
                    {% endif %}
                    <div class="nav-link">
                        <span class="text-xl">
                            News
                        </span>
                    </div>
                    <div class="nav-link">
                        <span class="text-xl">
                            Contact Us
                        </span>
                    </div>
                    <div class="nav-link">
                        <button class="rounded p-2 bg-red-600 text-white text-lg text-center">
                              <a href="{% url 'crimereport' %}">
                                Report Crimes
                              </a>
                        </button>
                    </div>
                    {% if 'citizenID' in request.session %}
                    <div class="nav-link relative w-1/12">
                        <div class="flex flex-row w-full justify-between">
                            <span class="flex items-center">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                    <path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z" />
                                </svg>
<!--                                <img src="{% static 'media/notOff.png' %}" onclick="function notification(){-->
<!--                                    $('.notification-off').toggle('hidden');$('.notification-on').toggle('hidden');-->
<!--                                } notification();" class="w-5 notification-off" alt="">-->
<!--                                <img src="{% static 'media/notOn.png' %}" onclick="function notification(){-->
<!--                                    $('.notification-on').toggle('hidden');$('.notification-off').toggle('hidden');-->
<!--                                } notification();" class="w-5 hidden notification-on" alt="">-->
                            </span>
                            <span class="text-xl">
                                <img src="{{request.session.citizenImage}}" onclick="function userTools(){
                                    $('.user-tools').toggle('hidden');
                                } userTools();" class="w-12 rounded-full" alt="">
                            </span>
                        </div>
                        <div class="user-tools w-40 p-2 flex flex-col bg-gray-100 absolute mt-2 hidden">
                            <div>
                                <span class="text-black text-base">
                                    {{request.session.citizenName}}
                                </span>
                            </div>
                            <hr class="my-2">
                            <div>
                                <span class="text-black">
                                    <a href="{% url 'CitizenApp:CitizenProfile' %}">
                                        Profile
                                    </a>
                                </span>
                            </div>
                            <hr class="my-2">
                            <div>
                                <span class="text-black">
                                    <a href="{% url 'CitizenApp:CitizenLogout' %}">
                                        Logout
                                    </a>
                                </span>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" class="text-black w-8 md:hidden cursor-pointer" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
                </svg>
            </div>
        </nav>
    </header>
    <main role="main" class="flex flex-col w-full z-0">
        {% if messages %}
            {% for message in messages%}
                {% if message.tags == 'error' %}
                    <div class="flex justify-center">
                        <div class="p-4 m-4 bg-red-300 w-2/3 text-red-800 rounded border-red-600 border-2">
                            <span>
                                {{message}}
                            </span>
                        </div>
                    </div>
                {% else %}
                    <div class="flex justify-center">
                        <div class="p-4 m-4 bg-green-300 w-2/3 text-green-800 rounded border-green-600 border-2">
                            <span>
                                {{message}}
                            </span>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif%}
        <div class="w-full overflow-x-hidden">
            {% block content %}
            <!-- body of the page you have selected -->
            {% endblock %}
        </div>
    </main>
    <div class="relative">
        <div class="custom-shape-divider-bottom-1657651798">
            <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
                <path d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z" class="shape-fill"></path>
            </svg>
        </div>
        <footer class="bg-gray-300 p-6">
        <div class="flex flex-col md:flex-row">
            <div class="w-full md:w-1/4 mx-4">
                <div class="brand-img flex items-center justify-center">
                    <img src="{% static 'media/policeLogo.png' %}" class="w-1/2 md:w-5/6" alt="">
                </div>
                <div class="socials flex flex-row m-4 justify-around">
                    <!--Facebook logo-->
                    <svg class="w-12 text-blue-600 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
                    </svg>
                    <!--Twitter logo-->
                    <svg class="w-12 text-blue-300 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"/>
                    </svg>
                    <!--Twitter logo-->
                </div>
                <div class="text-center m-2">
                    <span class="text-xs">
                        Copyright © 2022. Kenya Police Service
                    </span>
                </div>
            </div>
            <div class="w-full md:w-1/4 mx-4 flex-col">
                <div class="text-xl font-semibold">
                    <span>
                        Useful Links
                    </span>
                </div>
                <div class="flex flex-col my-4">
                    <a href="{% url 'CitizenApp:CitizenLogin' %}" class="text-sm md:text-base my-2">Login</a>
                    <a href="{% url 'crimereport' %}" class="text-sm md:text-base my-2">Report Crime</a>
                    <a href="{% url 'CitizenApp:CitizenProfile' %}" class="text-sm md:text-base my-2">Citizen Portal</a>
                    <a href="{% url 'PoliceOfficerApp:OfficerLogin' %}" class="text-sm md:text-base my-2">Officer Portal</a>
                </div>
            </div>
            <div class="w-full md:w-1/4 mx-4 flex-col">
                <div class="text-xl font-semibold">
                    <div class="flex flex-row">
                        <span class="">
                            Police Updates
                        </span>
                        <div title="Please enter your email below to receive updates of any police activities" >
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-4" fill="none"viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                        </div>
                    </div>

                </div>
                <div class="flex flex-col my-4">
                    <span class="text-xs">
                        Email:
                    </span>
                    <input name="" id="newsletterEmail" class="w-full my-2 p-2 resize-none rounded">
                    <button class="p-1 text-base bg-purple-700 text-white rounded">
                        Get updates
                    </button>
                </div>
            </div>
            <div class="w-full md:w-1/4 mx-4 flex-col">
                <div class="text-xl font-semibold">
                    <span class="">
                        Contact Us
                    </span>
                </div>
                <div class="flex flex-col my-4">
                    <span class="text-sm md:text-base" >Kenya Police Headquarters,</span>
                    <span class="text-sm md:text-base" >Vigilance House, Harambee Avenue,</span>
                    <span class="text-sm md:text-base" >PO BOX 30083,</span>
                    <span class="text-sm md:text-base" >Nairobi, Kenya.</span>
                    <span class="text-sm md:text-base" >Telephone: (020) 341411/6/8</span>
                </div>
            </div>
        </div>
    </footer>
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

<script src="{% static 'js/helpers.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

</html>

records/templates/records/caseapproval.html
{% extends "records/base.html" %}
{% block content %}
     <h2 style="text-align:center";>Welcome Back</h2>
     <small style="text-align:center";>Welcome Back!Please fill in your details</small>
 <form method="post">
        <div class="inputContainer">
           <label for="">Case ID:</label>

<select name="form" id="form">
  <option value="caseid"> </option>
     <option value="caseid"> </option>
  <option value="caseid"> </option>
</select>
        </div>
<br>
             <div class="inputContainer">
           <label for="">Officer ID:</label>

<select name="form" id="form">
  <option value="officerid"> </option>
     <option value="officerid"> </option>
  <option value="officerid"> </option>
</select>
        </div>
<br>
           <div class="inputContainer">
        	<label for="" class="label">National ID</label>
            <input type="text" name="text" class="text" placeholder="Enter their National ID" required>
        </div>
<br>
        <div class="inputContainer">
           <label for="">Case Status:</label>

<select name="caseStatus" id="caseStatus">
  <option value="approved">Approved</option>
     <option value="pending">Pending</option>
  <option value="denied">Denied</option>
</select>
        </div>
<br>
       <button>Submit</button>
</form>
{% endblock content %}

records/templates/records/dashboard.html
{% block content %}
<h2>Police Officer Dashboard</h2>
Welcome Officer John Doe
<br>
What do you want to do today?
{% endblock content %}