CitizenApp/urls.py
from django.urls import path, include
from . import views as citizen_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'CitizenApp'
urlpatterns = [
    path('profile/', citizen_views.CitizenProfile, name='CitizenProfile'),
    path('login/', citizen_views.CitizenLogin, name='CitizenLogin'),
    path('logout/', citizen_views.CitizenLogout, name='CitizenLogout'),
    path('EditCitizen/<int:id>', citizen_views.CitizenEdit, name='CitizenEdit'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, name='uploads')

PoliceOfficerApp/urls.py
from django.urls import path, include
from . import views as officer_views
from django.conf import settings
from django.conf.urls.static import static

app_name = "PoliceOfficerApp"
urlpatterns = [
    path('', officer_views.index, name='OfficerDashboard'),
    path('OfficersDisplay/', officer_views.OfficersDisplay, name='OfficersDisplay'),
    path('OfficerProfile/', officer_views.OfficerProfile, name='OfficerProfile'),
    path('CitizensDisplay/', officer_views.CitizensDisplay, name='CitizensDisplay'),
    path('CrimesDisplay/', officer_views.CrimesDisplay, name='CrimesDisplay'),
    path('criminalbooking/', officer_views.criminalbooking, name='criminalbooking'),
    path('CriminalsDisplay/', officer_views.CriminalsDisplay, name='CriminalsDisplay'),
    path('CrimeListDisplay/', officer_views.CrimeListDisplay, name='CrimeListDisplay'),
    path('PoliceStation/', officer_views.PoliceStation, name='PoliceStation'),
    path('ViewStations/', officer_views.ViewStations, name='ViewStations'),
    path('login/', officer_views.login, name='OfficerLogin'),
    path('addCrimes/', officer_views.addCrimes, name='addCrimes'),

    path('case/', officer_views.CaseIndex, name='CaseIndex'),

    path('casetransfer/<int:id>', officer_views.CaseTransfer, name='CaseTransfer'),
    path('ob/<int:id>', officer_views.obDisplay, name='ob'),
    path('viewCase/<int:id>', officer_views.ViewCase, name='ViewCase'),
    path('approveCase/<int:id>', officer_views.ApproveCase, name='ApproveCase'),
    path('viewOB/<int:id>', officer_views.ViewOB, name='ViewOB'),
    path('showStation/<int:id>', officer_views.ShowStation, name='ShowStation'),
    path('generateCase/<int:id>', officer_views.GenerateCase, name='GenerateCase'),
    # CriminalEdit and update paths
    path('EditCriminal/<int:id>', officer_views.CriminalEdit, name='CriminalEdit'),
    path('EditOfficer/<int:id>', officer_views.OfficerEdit, name='OfficerEdit'),

    path('OfficerRegister/', officer_views.OfficerRegister, name='OfficerRegister'),
    path('logout/', officer_views.OfficerLogout, name='OfficerLogout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

police_system/urls.py
from django.contrib import admin
from django.urls import path, include
from records import views as record_views
from django.conf import settings
from django.conf.urls.static import static

app_name='PoliceSystem'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('evidence/',record_views.evidence, name='evidence'),
    path('crimereport/', record_views.CrimeListDisplay, name='crimereport'),
    path('issueforms/', record_views.issueforms, name='issueforms'),
    path('signup/',record_views.signup, name='userSignUp'),
    path('',record_views.landingpage, name='index'),
    path('citizen/', include('CitizenApp.urls'), name='citizen'),
    path('policeofficer/', include('PoliceOfficerApp.urls'), name='policeofficer')
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

PoliceOfficerApp/models.py
from django.db import models

# Create your models here.

PoliceOfficerApp/forms.py
from django import forms
from records.models import Criminal as CriminalModel

# created a new form for all the fields in the Criminal Model
class EditForm(forms.ModelForm):

    class Meta:
        model = CriminalModel
        fields= "__all__"

PoliceOfficerApp/views.py
import json
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.hashers import check_password, make_password
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.utils.datastructures import MultiValueDictKeyError
from records.models import Officer as OfficerModel, Case as CaseModel, PoliceStation as PoliceStationModel, CrimeAnonymous as CrimeAnonymousModel, Crime as CrimeModel, Criminal as CriminalModel, Citizen as CitizenModel, CrimeList as CrimeListModel, OB as OBModel
from django.core.files.storage import FileSystemStorage


def PoliceStation(request):
    if request.method == "POST":
        if request.POST.get('statLocation') and request.POST.get('statAddress'):
            policeStation = PoliceStationModel(location=request.POST.get('statLocation'),
                                               address=request.POST.get('statAddress'),
                                               ocsID=request.session['officerID'])
            policeStation.save()
            stationID = policeStation.pk
            currentDate = datetime.now()
            stationNumber = '%s-%s-%s' % (stationID, policeStation.location, currentDate)
            policeStation.stationNumber = stationNumber
            policeStation.save()
            messages.success(request, 'Police Station has been added.')
            return render(request, 'PoliceOfficerApp/addStation.html', {'title': "Police Station"})
    else:
        return render(request, 'PoliceOfficerApp/addStation.html', {'title': "Police Station", 'pageID': 8})


def ViewStations(request):
    station = PoliceStationModel.objects.all()
    return render(request, 'PoliceOfficerApp/viewStations.html', {'title': 'View Police Stations', 'stations': station, 'pageID': 8})


def ShowStation(request, id):
    station = PoliceStationModel.objects.get(id=id)
    return render(request, 'PoliceOfficerApp/showStation.html', {'title': 'Show Station', 'station': station})


def CaseIndex(request):
    ob = OBModel.objects.filter(hasCase=0).all()
    currentStation=request.session['officerStation']
    cases = CaseModel.objects.filter(currentStation=currentStation).all()
    return render(request, 'Case/index.html', {'title': 'Case', 'obs': ob, 'cases': cases, 'pageID': 9})


def ApproveCase(request, id):
    if  request.session['officerRank'] == 'OCS':
        case = CaseModel.objects.get(id=id)
        case.caseStatus = 'APPROVED'
        try:
            case.save()
        except Exception as e:
            messages.error(request, e)
            return redirect('PoliceOfficerApp:CaseIndex')
        else:
            messages.success(request, "Case has been successfully approved.")
            return redirect('PoliceOfficerApp:CaseIndex')
    else:
        messages.error(request, 'You are not authorized to approve cases.')
        return redirect('PoliceOfficerApp:CaseIndex')

def CaseTransfer(request, id):
    case = CaseModel.objects.get(id=id)
    stations = PoliceStationModel.objects.all()
    if request.method == 'POST':
        if request.POST.get('stationID'):
            case.previousStation = case.currentStation
            case.currentStation = request.POST.get('stationID')
            try:
                case.save()
            except Exception as e:
                messages.error(request, e)
                return redirect('PoliceOfficerApp:CaseIndex')
            else:
                messages.success(request, "Case has been successfully transferred.")
                return redirect('PoliceOfficerApp:CaseIndex')
        else:
            messages.error(request, 'An error has occurred. Please contact the administrator.')
            return redirect('PoliceOfficerApp:CaseIndex')
    else:
        return render(request, 'Case/casetransfer.html', {'title': 'Case Transfer', 'case': case, 'stations': stations, 'pageID': 9})


def GenerateCase(request, id):
    case = CaseModel()
    case.officerID = request.session['officerID']
    case.obID = id
    case.caseStatus = 'PENDING'
    case.currentStation = request.session['officerStation']
    ob = OBModel.objects.get(id=id)

    try:
        case.save()
        currentDate = datetime.now()
        case.caseNumber = '%s-%s-%s' % ('CSF', case.pk, currentDate)
        case.save()
        ob.hasCase = case.pk
        ob.save()
    except Exception as e:
        messages.error(request, e)
        return redirect('PoliceOfficerApp:CaseIndex')
    else:
        messages.success(request, 'Case successfully generated.')
        return redirect('PoliceOfficerApp:CaseIndex')


def ViewCase(request, id):
    case = CaseModel.objects.get(id=id)
    ob = OBModel.objects.get(hasCase=case.pk)
    officer = OfficerModel.objects.get(id=ob.officerID)
    citizen = CitizenModel.objects.get(id=ob.citizenID)
    crime = CrimeModel.objects.get(hasOB=ob.pk)
    station = PoliceStationModel.objects.get(id=case.currentStation)
    try:
        criminal = CriminalModel.objects.get(crimeID=crime.pk)
    except Exception as e:
        return render(request, 'Case/viewCase.html', {'title': 'View Case','case':case,'citizen':citizen,'ob':ob,'crime':crime,'officer':officer,'criminal':None,'station':station})
        #return redirect("PoliceOfficerApp:CaseIndex")
    else:
        criminalImages = []
        if criminal.criminalImage is not None:
            for file in json.loads(criminal.criminalImage):
                criminalImages.append(file)
        crimeSceneImages = []
        crimeSceneVideos = []
        if crime.files is not None:
            for file in json.loads(crime.files):
                fileExtension = (file).split(".", 1)[1]
                if fileExtension == 'jpg' or fileExtension == 'jpeg' or fileExtension == 'JPEG' or fileExtension == 'JPG':
                    crimeSceneImages.append(file)
                else:
                    crimeSceneVideos.append(file)
        return render(request, 'Case/viewCase.html', {'title': 'View Case','case':case,'crimeSceneVideos':crimeSceneVideos,'crimeSceneImages':crimeSceneImages,'criminalImages':criminalImages,'citizen':citizen,'ob':ob,'crime':crime,'officer':officer,'criminal':criminal,'station':station})

def addCrimes(request):
    if request.method == 'POST':
        if request.POST.get('crimeName'):
            saverecord = CrimeListModel()
            saverecord.crimeName = request.POST.get('crimeName')
            try:
                saverecord.save()
            except Exception as e:
                messages.error(request, e)
                return render(request, 'PoliceOfficerApp/addCrimes.html')
            else:
                messages.success(request, 'Crime has been added successfully!')
                return render(request, 'PoliceOfficerApp/addCrimes.html')
    else:
        return render(request, 'PoliceOfficerApp/addCrimes.html', {'title': 'Crime Report', 'pageID': 5})


# calls the EditCriminal page and the details of the row you want to CriminalEdit are prefilled
def CriminalEdit(request, id):
    CriminalsDisplay = CriminalModel.objects.get(id=id)
    if request.method == 'POST':
        if request.POST.get('criminalFName') and \
                request.POST.get('criminalLName') and \
                request.POST.get('criminalPhone') and \
                request.POST.get('criminalAddress') and \
                request.POST.get('criminalIDNo') and \
                request.POST.get('criminalGender') and \
                request.POST.get('crimeID') and \
                request.POST.get('criminalStatus') and \
                request.POST.get('arrestLocation') and \
                request.POST.get('arrestDate'):
            CriminalsDisplay.fName = request.POST.get('criminalFName')
            CriminalsDisplay.lName = request.POST.get('criminalLName')
            CriminalsDisplay.tel = request.POST.get('criminalPhone')
            CriminalsDisplay.address = request.POST.get('criminalAddress')
            CriminalsDisplay.nationalID = request.POST.get('criminalIDNo')
            CriminalsDisplay.gender = request.POST.get('criminalGender')
            CriminalsDisplay.crimeID = request.POST.get('crimeID')
            CriminalsDisplay.criminalStatus = request.POST.get('criminalStatus')
            CriminalsDisplay.locationArrested = request.POST.get('arrestLocation')
            CriminalsDisplay.arrestDate = request.POST.get('arrestDate')
            try:
                CriminalsDisplay.save()
            except Exception as e:
                messages.error(request, e)
                return render(request, 'PoliceOfficerApp/EditCriminal.html')
            else:
                messages.success(request, 'Criminal has been updated!')
                return redirect('PoliceOfficerApp:CriminalsDisplay')
        else:
            return render(request, 'PoliceOfficerApp/EditCriminal.html', {'CriminalsDisplay': CriminalsDisplay})
    else:
        return render(request, 'PoliceOfficerApp/EditCriminal.html', {'CriminalsDisplay': CriminalsDisplay})


def obDisplay(request, id):
    CrimesDisplay = CrimeModel.objects.get(id=id)
    if request.method == 'POST':
        if request.POST.get('obAction') and request.POST.get('citizenID') and request.POST.get('crimeID'):
            try:
                filepath = request.FILES['document']
            #This exception handles when there is no file uploaded
            except MultiValueDictKeyError:
                ob = OBModel(citizenID=request.POST.get('citizenID'),
                             crimeID=request.POST.get('crimeID'),
                             reportDate=request.POST.get('reportDate'),
                             actionTaken=request.POST.get('obAction'),
                             officerID=request.session['officerID'])
                try:
                    ob.save()
                    obID = ob.pk
                    obNumber = '%s/%s/%s' % (obID, datetime.now(), request.POST.get('citizenID'))
                    ob.obNo = obNumber

PoliceOfficerApp/templates/Case/casetransfer.html
{% extends "PoliceOfficerApp/base.html" %}
{% block content %}
    <div class="flex justify-center w-full">
        <div class="my-20 w-1/2 rounded-lg flex flex-row">
            <div class="w-full p-4 bg-gray-100 rounded-l-lg">
                <div class="form-container w-2/3 m-auto flex flex-col justify-center my-4">
                    <div class="flex flex-col my-10">
                        <div class="flex flex-col">
                            <span class="text-4xl">
                                Case Transfer
                            </span>
                        </div>
                    </div>
                    <form action="" method="POST" class="flex flex-col w-full">
                        {% csrf_token %}
                        <div class="form-group w-full flex flex-col my-4">
                            <div class="form-label">
                                <label for="stationID" class="text-base my-2">
                                 Receiving Police Station
                                </label>
                            </div>
                            <div class="form-input my-2 flex">
                                    <select name="stationID" id="stationID" class="w-full p-2 rounded hover:border-blue invalid:border-red-500 valid:border-green-500 required:border-red-500 border-2">
                                        {% for station in stations %}
                                            {% if case.currentStation != station.id %}
                                                <option value="{{station.id}}">{{station.location}} Police Station</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                            </div>

                         <div class="form-group w-full flex flex-col my-4">
                            <div class="form-label">
                                <label for="caseNo" class="text-base my-2">
                                 Case Number
                                </label>
                            </div>
                            <div class="form-input my-2 flex">
                                <input type="text" id="caseNo" value="{{case.caseNumber}}" disabled name="caseNo" required class="w-full select-none p-2 rounded hover:border-blue invalid:border-red-500 valid:border-green-500 required:border-red-500 border-2">
                            </div>
                         </div>

                        <div class="form-button w-full flex flex-col my-4">
                            <button name="addCrime" class="p-2 text-center w-full rounded bg-blue-600 text-white text-lg">
                               Approve Case Transferal
                            </button>
                        </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

PoliceOfficerApp/templates/Case/index.html
{% extends "PoliceOfficerApp/base.html" %}
{% block content %}
<h2 class="text-center"><a class="text-blue-500" href="#"> View Cases </a> </h2>

<div class="relative m-2 flex flex-col h-full w-full gap-y-20">
    <div class="flex flex-row w-full h-96 justify-between">
        <div class="bg-white rounded w-5/12">
            <div class="case-header text-center py-2">
                <span class="text-xl">
                    Available OBs
                </span>
            </div>
            <div class="m-2">
                <table class=" text-center w-full text-sm text-left text-gray-500 dark:text-gray-400 table-auto">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th>
                                OB Number
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for ob in obs %}
                        <tr class="border-b bg-gray-100 hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-50 odd:dark:bg-gray-800 even:dark:bg-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                            <td class="px-6 py-4">
                                {{ob.obNo}}
                            </td>
                            <td class="px-6 py-4">
                                <a href="{% url 'PoliceOfficerApp:GenerateCase' ob.id %}">
                                    <button class="bg-blue-500 text-white p-2 rounded" name="generateCase">
                                        Generate Case
                                    </button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="bg-white rounded w-5/12">
            <div class="case-header text-center py-2">
                <span class="text-xl">
                    Available Cases
                </span>
            </div>
            <div class="m-2">
                <table class=" text-center w-full text-sm text-left text-gray-500 dark:text-gray-400 table-auto">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th>
                                Case Number
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for case in cases %}
                        <tr class="border-b bg-gray-100 hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-50 odd:dark:bg-gray-800 even:dark:bg-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                            <td class="px-6 py-4">
                                {{case.caseNumber}}
                            </td>
                            <td class="px-6 py-4">
                                <a href="{% url 'PoliceOfficerApp:CaseTransfer' case.id%}">
                                    <button class="bg-blue-500 text-white p-2 rounded" name="generateCase">
                                        Transfer Case
                                    </button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="flex flex-row w-full h-96 justify-between">
        <div class="bg-white rounded w-5/12">
            <div class="case-header text-center py-2">
                <span class="text-xl">
                    Pending Cases
                </span>
            </div>
            <div class="m-2">
                <table class=" text-center w-full text-sm text-left text-gray-500 dark:text-gray-400 table-auto">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th>
                                Case Number
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for case in cases %}
                        {% if case.caseStatus == 'PENDING' %}
                        <tr class="border-b bg-gray-100 hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-50 odd:dark:bg-gray-800 even:dark:bg-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                            <td class="px-6 py-4">
                                {{case.caseNumber}}
                            </td>
                            <td class="px-6 py-4">
                                <a href="{% url 'PoliceOfficerApp:ApproveCase' case.id%}">
                                    <button class="bg-blue-500 text-white p-2 rounded" name="generateCase">
                                        Approve Case
                                    </button>
                                </a>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="bg-white rounded w-5/12">
            <div class="case-header text-center py-2">
                <span class="text-xl">
                    Approved Cases
                </span>
            </div>
            <div class="m-2">
                <table class=" text-center w-full text-sm text-left text-gray-500 dark:text-gray-400 table-auto">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th>
                                Case Number
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for case in cases %}
                        {% if case.caseStatus == 'APPROVED' %}
                        <tr class="border-b bg-gray-100 hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-50 odd:dark:bg-gray-800 even:dark:bg-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                            <td class="px-6 py-4">
                                {{case.caseNumber}}
                            </td>
                            <td class="px-6 py-4">
                                <a href="{% url 'PoliceOfficerApp:ViewCase' case.id%}">
                                    <button class="bg-blue-500 text-white p-2 rounded" name="generateCase">
                                        View Case
                                    </button>
                                </a>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}